# netlify.toml

[build]
  command = "pip install -r requirements.txt"
  publish = "public"
  functions = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify_handler"
  status = 200
