# netlify.toml

[build]
  command = "pip install -r requirements.txt"
  functions = "functions/" # The folder where your function file is

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify_handler"
  status = 200